version: "2.0"
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    links:
      - elasticsearch
  logstash_test:
    image: docker.elastic.co/logstash/logstash:5.6.3
    ports:
      - "10000:10000"
    links:
      - elasticsearch
    volumes:
      - ./logstash_settings/:/usr/share/logstash/config/
      - ./logstash_pipeline/:/usr/share/logstash/pipeline/
      - /EGOV/eclipse-jee-oxygen/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/logs/:/usr/share/logstash/logs/
    container_name: logstash_test
networks:
  docker_elk:
    driver: bridge