version: '2'
services:
  zookeeper_log:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper_log
  kafka_log:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      # The below only works for a macOS environment if you installed Docker for
      # Mac. If your Docker engine is using another platform/OS, please refer to
      # the relevant documentation with regards to finding the Host IP address
      # for your platform.
#      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
#      KAFKA_ADVERTISED_HOST_NAME: 'kafka.docker.ssl'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_log:2181
      KAFKA_CREATE_TOPICS: "logstash_logs:1:1"
#      KAFKA_BROKER_ID: 300
    links:
      - zookeeper_log
    depends_on:
      - zookeeper_log
    container_name: kafka_log
  logstash_1st:
    image: docker.elastic.co/logstash/logstash:5.6.3
    ports:
      - "10000:10000"
    links:
      - kafka_log
      - kafka_log:kafka
    volumes:
      - ./logstash_settings1/:/usr/share/logstash/config/
      - ./logstash_pipeline1/:/usr/share/logstash/pipeline/
      - /EGOV/eclipse-jee-oxygen/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/logs/:/usr/share/logstash/logs/
    container_name: logstash_1st
  logstash_2nd:
    image: docker.elastic.co/logstash/logstash:5.6.3
    ports:
      - "20000:20000"
    links:
      - kafka_log
      - kafka_log:kafka
      - elasticsearch_log
      - elasticsearch_log:elasticsearch
    volumes:
      - ./logstash_settings2/:/usr/share/logstash/config/
      - ./logstash_pipeline2/:/usr/share/logstash/pipeline/
    container_name: logstash_2nd
  elasticsearch_log:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch_log
  kibana_log:
    image: kibana:latest
    ports:
      - "5601:5601"
    links:
      - elasticsearch_log
      - elasticsearch_log:elasticsearch
    container_name: kibana_log
networks:
  default:
    external:
      name: kafka-logstash-docker_default